title       = "datacite"
baseURL     = "https://datacite-cli.tamnd.com/"
description = "A command line for datacite."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/datacite-cli"
